### ISSUE TITLE
ENV variables

### ISSUE THREAD

**Issue by stevkim** [panda-express-js/FEC#112]
https://github.com/panda-express-js/FEC/blob/73c46e6a571b4171b2f23c64ad3a88c06a3ab5c7/client/src/components/App.jsx#L35C8-L35C9

Do you want this URL public?

Not just this but your Github APIKEY will also be public.
When in production, you'll need to create a server to mask the sensitive information.
For tokens, since the request is coming from your client-side, it will be exposed in the network tab.

**Comment by FloraLZhang** [comment]
build up express server file to handle request and the authorization
